argeportal/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('register/', include('register.urls', namespace='register')),
    # path('projects/', include('projects.urls', namespace='projects')),
    path('', include('core.urls', namespace='core')),
]

core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),
    path('personel/addpersonel/', views.addPersonel, name='addpersonel'),
    path('personel/personelmain/', views.personelMain, name='personelmain'),
    path('personel/personelmain/detail/<int:id>', views.personelDetail, name='personeldetail'),
    path('personel/personelmain/update/<int:id>', views.personelUpdate, name='personelupdate'),
    path('personel/personelmain/export', views.exportPersonel, name='exportPersonel'),
    path('personel/personelmain/exportperson/<int:id>', views.exportPerson, name='exportPerson'),
    path('personel/personalstable/', views.personalstable, name='personalstable'),
    path('charts/personel', views.chartPersonel, name='chartPersonel'),
    path('charts/projects', views.chartProjects, name='chartProjects'),
    path('chartPersonelview', views.chartPersonelview, name='chartPersonelview'),
    path('charts/', views.argePano, name="argepano"),
    path('news/', views.news, name='news'),
    path('news/newstable', views.newstable, name='newstable'),
    path('news/<int:id>', views.newsDetail, name='newsdetail'),
    path('news/addnews/', views.addNews, name='addnews'),
    path('news/update/<int:id>', views.updateNews, name='updatenews'),
    path('news/delete/<int:id>', views.deleteNews, name='deletenews'),
    path('projects/projectsmain', views.projectsMain, name="projectsmain"),
    path("projects/addproject",views.addproject, name="addproject"),
    path('projects/projectsmain/detail/<int:id>', views.projectDetail, name="projectdetail"),
    path('projects/projectsmain/update/<int:id>', views.projectUpdate, name="projectupdate"),
    path('projects/projectsmain/export', views.exportProjects, name='exportprojects'),
    path('projects/projectsmain/exportproject/<int:id>', views.exportProject, name='exportproject'),
    path('projects/projectstable/', views.projectstable, name='projectstable'),
    path('maintance/departmentstable/', views.departmentstable, name='departmentstable'),
    path('maintance/adddepartments/', views.adddepartments, name='adddepartments'),
    path('projects/adamaymain', views.adamayMain, name='adamaymain'),
    path('projects/adamaybase', views.adamayBase, name='adamaybase'),
    path('projects/addmanmonth/<int:id>', views.addManmonth, name='addmanmonth'),
    path('projects/addmanmonthid/<int:id>', views.addManmonthid, name='addmanmonthid'),
    path('projects/addispaketi/', views.addispaketi, name='addispaketi'),
    path('projects/projectsmain/projeispaketi/<int:id>', views.projeispaketi, name='projeispaketi'),
    path('projects/projectsmain/projeispaketi/update/<int:id>', views.projeispaketiupdate, name='projeispaketiupdate'),
    path('argetesvik/', views.argetesvik, name='argetesvik'),
    path('argetesvik/ekle', views.argetesvikekle, name='argetesvikekle'),
    path('argetesvik/duzenle/<int:id>', views.argetesvikduzenle, name='argetesvikduzenle'),
    path('argetesvik/sil/<int:id>', views.argetesviksil, name='argetesviksil'),
    path('fikrimulkiyet/', views.patent, name='patent'),
    path('patent/ekle', views.patentekle, name='patentekle'),
    path('patent/duzenle/<int:id>', views.patentduzenle, name='patentduzenle'),
    path('patent/sil/<int:id>', views.patentsil, name='patentsil'),
    path('bildiri/ekle', views.bildiriekle, name='bildiriekle'),
    path('bildiri/duzenle/<int:id>', views.bildiriduzenle, name='bildiriduzenle'),
    path('bildiri/sil/<int:id>', views.bildirisil, name='bildirisil'),
    path('api/data', views.apiData, name='apiData'),
    
    # path('dashboard/', views.dashboard, name='dashboard'),
    # path('login/', views.login_view, name='login'),
    # path('logout/', views.logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from django.http import JsonResponse
from .forms import PersonelForm,NewsForm, ProjectsForm, AdamAyForm, IsPaketiekleForm, ArgetesvikForm, PatentekleForm, BildiriekleForm
from .models import Personel, News, Projects, DepartmentList, IsPaketiekle, AdamAy, ArgeTesvik, Patent, Bildiri
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import csv,datetime,xlwt
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Avg, Sum, F, Case, When, IntegerField, ExpressionWrapper, CharField
from django.db.models.functions import TruncMonth, TruncYear, TruncQuarter
from datetime import timedelta
from django.forms import modelformset_factory
import math, copy
from copy import deepcopy
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.template.defaulttags import register
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger 



# Create your views here.
"""def index(request):
    news = News.objects.all()
    news1 = news.order_by('updateDate')[0]
    news2 = news.order_by('updateDate')[1]
    news3 = news.order_by('updateDate')[2]
    news4 = news.order_by('updateDate')[3]
    news5 = news.order_by('updateDate')[4]
    news6 = news.order_by('updateDate')[5]
    
    context = {
        "news" : news,
        "news1" : news1,
        "news2" : news2,
        "news3" : news3,
        "news4" : news4,
        "news5" : news5,
        "news6" : news6,
    }

    a= news.order_by('updateDate')[5]
    print(a)
    
    for x in a:
        d =x.title
        print(d)

    return render(request, 'core/index.html',context)"""

def index(request):
    today=datetime.date.today()
    personels_active=Personel.objects.filter(rdfinisDate__isnull=True)
    projects_active=Projects.objects.filter(ProjeDurumu=1)
    projects_finished=Projects.objects.filter(ProjeDurumu=2)
    projects_national=Projects.objects.filter(UlusalDestek=True)
    harcama = ArgeTesvik.objects.aggregate(outcome=Sum('argetotal'), income=Sum('hibe'), totaltesvik=Sum('ayliktesviktoplam'), avrtesvik=Avg('ayliktesvikyuzde'))
    argetesvik=ArgeTesvik.objects.all()
    argetesvik_thisyear=ArgeTesvik.objects.filter(date__year__gte=today.year)
    argetesvik_last3year=ArgeTesvik.objects.filter(date__year__gte=today.year-2)
    personel_dep = Personel.objects.filter(rdfinisDate__isnull=True).values('department','department__name').annotate(Count('department'))
    
    # Fikri Hak Dağılımı Chart
    fikrihak = Patent.objects.values('model').annotate(Count('model'))
    for i in fikrihak:
        i['model_display']=Patent(model=i['model']).get_model_display()
    
    # Yayın / Bildiri Chart
    bildiri = Bildiri.objects.values('typ').annotate(Count('typ'))
    for i in bildiri:
        i['bildiri_display']=Bildiri(typ=i['typ']).get_typ_display()
    print(bildiri)

    # Cinsiyet Dağılımları Chart
    personel_gender = Personel.objects.filter(rdfinisDate__isnull=True).values('gender').annotate(Count('gender'))
    for sex in personel_gender:
        sex['gender_display']=Personel(gender=sex['gender']).get_gender_display()
    

    # Görev Dağılımları Chart
    personel_respons = Personel.objects.filter(rdfinisDate__isnull=True).values('respons').annotate(Count('respons'))
    for respons in personel_respons:
        respons['respons_display'] = Personel(respons=respons['respons']).get_respons_display()
    
    # Eğitim Dağılımları Chart
    personel_education = Personel.objects.filter(rdfinisDate__isnull=True).values('graduated').annotate(Count('graduated'))
    for education in personel_education:
        education['education_display']=Personel(graduated=education['graduated']).get_graduated_display()
    
    context = {
        "personels_active" : personels_active,
        "projects_active" : projects_active,
        "projects_finished" : projects_finished,
        "projects_national" : projects_national,
        "harcama" : harcama,
        "argetesvik" : argetesvik,
        "argetesvik_thisyear" : argetesvik_thisyear,
        "personel_dep" : personel_dep,
        "personel_gender" : personel_gender,
        "personel_respons" : personel_respons,
        "personel_education" : personel_education,
        "argetesvik_last3year" : argetesvik_last3year,
        "fikrihak" : fikrihak,
        "bildiri" : bildiri,
    }

    return render(request, 'core/index.html',context)

def argetesvik(request):
    today=datetime.date.today()
    harcama = ArgeTesvik.objects.aggregate(outcome=Sum('argetotal'), income=Sum('hibe'), totaltesvik=Sum('ayliktesviktoplam'), avrtesvik=Avg('ayliktesvikyuzde'))
    argetesvik_last=ArgeTesvik.objects.filter(date__year=today.year)
    argetesvik_last1=ArgeTesvik.objects.filter(date__year=today.year - 1)
    argetesvik_last3=ArgeTesvik.objects.filter(date__year__gte=today.year - 2)
    tesvikverileri = ArgeTesvik.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(tesvikverileri, 10)
    try:
        tesvikverileri = paginator.page(page)
    except PageNotAnInteger:
        tesvikverileri = paginator.page(1)
    except EmptyPage:
        tesvikverileri = paginator.page(paginator.num_pages)

    
    context = {
        "harcama" : harcama,
        "argetesvik_last" : argetesvik_last, 
        "argetesvik_last1" : argetesvik_last1,
        "argetesvik_last3" : argetesvik_last3,
        "tesvikverileri" : tesvikverileri,
    }
    return render(request,"core/argetesvik.html", context)

def argetesvikekle(request):
    if request.method == 'POST':
        form = ArgetesvikForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Kayıt Başarılı')
            return redirect('core:argetesvik')
    else:
        form = ArgetesvikForm()
        return render(request, "core/argetesvikekle.html", {"form":form})

def argetesvikduzenle(request, id):
    instance = get_object_or_404(ArgeTesvik, id=id)
    if request.method == 'POST':
        form = ArgetesvikForm(request.POST, instance = instance)
        if form.is_valid():
            form.save()
            messages.success(request,'Teşvik Verilerinin Güncellemesi Başarılı')
            return redirect('core:argetesvik')
    else:
        form = ArgetesvikForm(instance=instance)
        return render(request, 'core/argetesvikduzenle.html', {"form":form, "id":id})
    
def argetesviksil(request, id):
    deletedobject = ArgeTesvik.objects.get(id=id)
    deletedobject.delete()
    messages.success(request,"Kayıt Başarıyla Silindi")
    return redirect('core:argetesvik')

# --PATENT--FİKRİ MULKIYET--
def patent(request):
    patent = Patent.objects.all()
    bildiri = Bildiri.objects.all()
    patenBasvur = Patent.objects.filter(model=1,apldate__isnull=False).values('area').annotate(Count('area'))
    patenTescil = Patent.objects.filter(model=1,apldate__isnull=False, aprdate__isnull=False).values('area').annotate(Count('area'))
    modelBasvur = Patent.objects.filter(model=2,apldate__isnull=False).values('area').annotate(Count('area'))
    modelTescil = Patent.objects.filter(model=2,apldate__isnull=False, aprdate__isnull=False).values('area').annotate(Count('area'))
    bildiriTescil = Bildiri.objects.values('area').annotate(Count('area'))
    patentsum = Patent.objects.annotate(year=TruncYear('apldate')).values('year').annotate(ulusalp=Sum(Case(When(area=1, model=1, then=1),output_field=IntegerField())),uluslararasip=Sum(Case(When(area=2, model=1, then=1), output_field=IntegerField())),ulusalm=Sum(Case(When(area=1, model=2, then=1),output_field=IntegerField())),uluslararasim=Sum(Case(When(area=2, model=2, then=1), output_field=IntegerField())))
    bildirisum = Bildiri.objects.annotate(year=TruncYear('pubdate')).values('year').annotate(ulusalm=Sum(Case(When(area=1, typ=0, then=1),output_field=IntegerField())),uluslararasim=Sum(Case(When(area=2, typ=0, then=1), output_field=IntegerField())),ulusalb=Sum(Case(When(area=1, typ=1, then=1),output_field=IntegerField())),uluslararasib=Sum(Case(When(area=2, typ=1, then=1), output_field=IntegerField())),ulusalp=Sum(Case(When(area=1, typ=1, then=1),output_field=IntegerField())),uluslararasip=Sum(Case(When(area=2, typ=2, then=1), output_field=IntegerField())))
    page = request.GET.get('page', 1)
    paginator = Paginator(patent, 5)
    try:
        patent = paginator.page(page)
    except PageNotAnInteger:
        patent = paginator.page(1)
    except EmptyPage:
        patent = paginator.page(paginator.num_pages)

    context={
        "patent" : patent,
        "bildiri" : bildiri,
        "patenBasvur" : patenBasvur,
        "patenTescil" : patenTescil,
        "modelBasvur" : modelBasvur,
        "modelTescil" : modelTescil,
        "bildiriTescil" : bildiriTescil,
        "patentsum" : patentsum,
        "bildirisum" : bildirisum,
    }
    return render(request,"core/fikrimulkiyet.html", context)

def patentekle(request):
    form = PatentekleForm()
    if request.method=='POST':
        form = PatentekleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request,'Patent/Faydalı Model Kaydı Başarılı')
            return redirect('core:patent')
        else:
            messages.warning(request,'Kayıt Başarısız')
            return redirect('core:patentekle')
    else:
        return render(request, 'core/patentekle.html', {"form" : form})

def patentduzenle(request, id):
    instance = get_object_or_404(Patent, id=id)
    if request.method=='POST':
        form = PatentekleForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            messages.success(request,'Düzenleme Başarılı')
            return redirect('core:patent')
        else:
            messages.warning(request, 'Düzenleme Başarısız')
    else:

templates/core/includes/adamaybaseinc.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block breadcrumb %}
        <li class="breadcrumb-item"><a  href="{% url 'core:index' %}" >Ana Sayfa</a></li>
        <li class="breadcrumb-item passive">Adam-Ay Liste</li>
{% endblock breadcrumb %}


{% block breadcrumb_menu %}
    {% if user.is_authenticated  %}
    <a class="btn btn-gray-100 btn-outline-blue", href="{% url 'core:adamaymain' %}"><i class="fa fa-diagnoses"></i> Proje Adam/Ay Ekle</a>
    <a class="btn btn-gray-100 btn-outline-blue", href="{% url 'core:exportprojects' %}"><i class="fa fa-download"></i>  Export</a>
    {% endif %}
{% endblock breadcrumb_menu %}

{% block content %}
<div class="col-sm-10 offset-1">
    <div class="card">
        <div class="card-header">
            {% if today %}
            <i class="fa fa-calendar"></i><strong>{{today|date:"Y F"}}  Adam/Ay Listesi</strong>
            {% else %}
            <i class="fa fa-calendar"></i><strong>{{year}} {{month}} 'inci Ay Adam/Ay Listesi</strong>
            {% endif %}
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-12">
                    <p>İstemiş Olduğunuz Ayı Seçerek O Aya Ait Tüm Adam/Ay Oranlarını Listeleyebilirsiniz...</p>
                    <form>
                        {% csrf_token %}
                        <div class="input-group">
                        <input type="date", name="keyword", class="input-group-sm form-control", maxlength="64", placeholder="Ara">
                        <button type="submit", class="btn btn-gray-100 btn-outline-blue"><i class="fa fa-search"></i> Dönem Ara</button>
                        </div>
                    </form>
                    </div>
                <br>
                    <table class="table table-responsive-sm table-hover table-outline mb-5 ">
                        <thead class="thead-light">
                            <tr>
                                <th class="text-center"><i class="fa fa-user"></i></th>
                                <th>Personel</th>
                                <th class="text-center">Adam/Ay Oranı</th>
                                <th class="text-center">Atanılmış Proje</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for query in queryset %}
                            <tr>
                                <td class="text-center">
                                    <div class="avatar">
                                        {% if query.user_img %}
                                            <img src="{% get_media_prefix %}{{query.user_img}}" class="img-avatar" alt="blabla">
                                        {% else %}
                                            <img src="{% static 'core/avatar/blank_profile.png' %}" class="img-avatar">
                                        {% endif %}
                                    </div>
                                </td>
                                <td><a href="addmanmonthid/{{query.id}}">{{query.projeAdamAy__name}} {{query.projeAdamAy__surName}}</a></td>
                                <td>
                                <div class="clearfix">
                                    <div class="float-left">
                                        <strong>{% widthratio query.total_manmonth 1 100%}%</strong>
                                    </div>
                                    <div class="float-right">
                                        <small class="text-muted">Adam Ay</small>
                                    </div>
                                </div>
                                    {% if query.total_manmonth > 1 %}
                                    <div class = "progress progress-xs">
                                        <div class="progress-bar bg-danger" role="progressbar" style="width: {% widthratio query.total_manmonth 1 100 %}%" aria-valuenow="74" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    {% elif query.total_manmonth == 1 %}
                                    <div class = "progress progress-xs">
                                        <div class="progress-bar bg-succes" role="progressbar" style="width: {% widthratio query.total_manmonth 1 100 %}%" aria-valuenow="74" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    {% else %}
                                    <div class = "progress progress-xs">
                                        <div class="progress-bar bg-warning" role="progressbar" style="width: {% widthratio query.total_manmonth 1 100 %}%" aria-valuenow="74" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    {% endif %}
                                </td>
                                <td class="text-center"><span class="badge badge-pill badge-dark"> {{query.total_project}}</span></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

 {% endblock content %}
 

templates/core/includes/navbar.html
{% load static %}

<header class="app-header navbar">
    <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a href="{% url 'core:index' %}" ><img src="{% static 'core/img/logos/arge-horizontal.png' %}" alt="" class="brand-gui ml-2 d-none d-sm-block p-2"></a>
    <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>

    <ul class="nav navbar-nav d-md-down-none">
      <li class="nav-item px-3">
        <a class="nav-link" href="{% url 'core:index' %}">Ana Sayfa</a>
      </li>
      <li class="nav-item px-3">
        <a class="nav-link" href="#">Hakkımızda</a>
      </li>
      <li class="nav-item px-3">
        <a class="nav-link" href="{% url 'core:argepano' %}">Ar-Ge Göstergeleri</a>
      </li>
      <li class="nav-item px-3">
        <a class="nav-link" href="{% url 'core:news' %}">Haberler</a>
      </li>
    </ul>
    <ul class="nav navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="text-muted">Merhaba, {{ user.first_name }}</li>
      {% else %}
      <li class="text-muted">
        <a href="#">Kayıt Ol</a>
      </li>
      {% endif %}
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          {% if user.is_authenticated %}
          <img src="{% static 'core/img/avatar/user1.jpg' %}" class="img-avatar" alt="{{ user }}">
          {% else %}
          <img src="{% static 'core/img/avatar/blank_profile.png' %}" class="img-avatar" alt="{{ user }}">
          {% endif %}
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <div class="dropdown-header text-center">
            <strong>Hesap</strong>
          </div>
          {% if user.is_authenticated %}
          <a class="dropdown-item" href="#"><i class="fa fa-tasks"></i>Görevler<span class="badge badge-danger">{{ user.task_set.values.count }}</span></a>
          <!--<a class="dropdown-item" href="#"><i class="fa fa-comments"></i> Comments<span class="badge badge-warning">42</span></a>-->
          <div class="dropdown-header text-center">
            <strong>Ayarlar</strong>
          </div>
          <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Profil</a>
          <div class="divider"></div>
          <!--<a class="dropdown-item" href="#"><i class="fa fa-shield"></i> Lock Account</a>-->
          <a class="dropdown-item" href="#"><i class="fa fa-lock"></i> Çıkış Yap</a>
          {% else %}
          <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Giriş Yap</a>
          {% endif %}
        </div>
      </li>
    </ul>
  </header>

templates/core/includes/sidebar.html
{% load static %}

<div class="app-body">
    <div class="sidebar">
      <nav class="sidebar-nav">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:index' %}"><i class="fa fa-home"></i> Ana Sayfa</a>
          </li>
          <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-chart-bar"></i> Göstergeler</a>
            <ul class="nav-dropdown-items">
            <li class="nav-item">
              <a class="nav-link" href="#"><i class="fa fa-trophy"></i> Proje </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:chartPersonel' %}"><i class="fa fa-diagnoses"></i> Personel </a>
            </li>
            </ul>
          </li>
          <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-tachometer-alt"></i> Ar-Ge Panosu</a>
            <ul class="nav-dropdown-items">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:projectsmain' %}"><i class="fa fa-paper-plane ml-2"></i> Projeler</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:personelmain' %}"><i class="fa fa-user ml-2"></i> Personeller</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:adamaybase' %}"><i class="fa fa-diagnoses ml-2"></i> Adam Aylar</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:argetesvik' %}"><i class="fa fa-wallet ml-2"></i> Teşvik </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:patent' %}"><i class="fa fa-book-open ml-2"></i> Fikri Mülkiyet </a>
              </li>
            </ul>
          </li>

          <!--<li class="nav-title">-->
            <!--Theme-->
          <!--</li>-->
          <!--<li class="nav-item">-->
            <!--<a href="colors.html" class="nav-link"><i class="fa fa-tint"></i> Colors</a>-->
          <!--</li>-->
          <!--<li class="nav-item">-->
            <!--<a href="typography.html" class="nav-link"><i class="fa fa-user"></i> Typograhy</a>-->
          <!--</li>-->
          <li class="nav-title">
            Admin Paneli
          </li>
          <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-plus-square"></i> Eklemeler</a>
            <ul class="nav-dropdown-items">
              <li class="nav-item">
                <a class="nav-link" href="#"><i class="fa fa-plus ml-2"></i> Haber Ekle</a>
                <a class="nav-link" href="#"><i class="fa fa-plus ml-2"></i> Personel Ekle</a>
                <a class="nav-link" href="{% url 'core:addproject' %}"><i class="fa fa-plus ml-2"></i> Proje Ekle</a>
                <a class="nav-link" href="#"><i class="fa fa-plus ml-2"></i> İş Paketi Ekle</a>
                <a class="nav-link" href="#"><i class="fa fa-plus ml-2"></i> Departman Ekle</a>
                <a class="nav-link" href="{% url 'core:adamaymain' %}"><i class="fa fa-street-view"></i> Proje Adam/Ay Ekle</a>
              </li>
            </ul>
          </li>
          <li class="nav-item nav-dropdown">
            <a class="nav-link nav-dropdown-toggle" href="#"><i class="fa fa-puzzle-piece"></i> Raporlar</a>
              <ul class="nav-dropdown-items">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:newstable' %}"><i class="fa fa-list ml-2"></i> Haber Listesi</a>
                  <a class="nav-link" href="{% url 'core:personalstable' %}"><i class="fa fa-list ml-2"></i> Personel Listesi</a>
                  <a class="nav-link" href="{% url 'core:projectstable' %}"><i class="fa fa-list ml-2"></i> Proje Listesi</a>
                  <a class="nav-link" href="{% url 'core:departmentstable' %}"><i class="fa fa-list ml-2"></i> Departman Listesi</a>
                </li>
              </ul>
          </li>
        </ul>
      </nav>
      <button class="sidebar-minimizer brand-minimizer" type="button"></button>
    </div>