argeportal/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('register/', include('register.urls', namespace='register')),
    # path('projects/', include('projects.urls', namespace='projects')),
    path('', include('core.urls', namespace='core')),
]

core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),
    path('personel/addpersonel/', views.addPersonel, name='addpersonel'),
    path('personel/personelmain/', views.personelMain, name='personelmain'),
    path('personel/personelmain/detail/<int:id>', views.personelDetail, name='personeldetail'),
    path('personel/personelmain/update/<int:id>', views.personelUpdate, name='personelupdate'),
    path('personel/personelmain/export', views.exportPersonel, name='exportPersonel'),
    path('personel/personelmain/exportperson/<int:id>', views.exportPerson, name='exportPerson'),
    path('personel/personalstable/', views.personalstable, name='personalstable'),
    path('charts/personel', views.chartPersonel, name='chartPersonel'),
    path('charts/projects', views.chartProjects, name='chartProjects'),
    path('chartPersonelview', views.chartPersonelview, name='chartPersonelview'),
    path('charts/', views.argePano, name="argepano"),
    path('news/', views.news, name='news'),
    path('news/newstable', views.newstable, name='newstable'),
    path('news/<int:id>', views.newsDetail, name='newsdetail'),
    path('news/addnews/', views.addNews, name='addnews'),
    path('news/update/<int:id>', views.updateNews, name='updatenews'),
    path('news/delete/<int:id>', views.deleteNews, name='deletenews'),
    path('projects/projectsmain', views.projectsMain, name="projectsmain"),
    path("projects/addproject",views.addproject, name="addproject"),
    path('projects/projectsmain/detail/<int:id>', views.projectDetail, name="projectdetail"),
    path('projects/projectsmain/update/<int:id>', views.projectUpdate, name="projectupdate"),
    path('projects/projectsmain/export', views.exportProjects, name='exportprojects'),
    path('projects/projectsmain/exportproject/<int:id>', views.exportProject, name='exportproject'),
    path('projects/projectstable/', views.projectstable, name='projectstable'),
    path('maintance/departmentstable/', views.departmentstable, name='departmentstable'),
    path('maintance/adddepartments/', views.adddepartments, name='adddepartments'),
    path('projects/adamaymain', views.adamayMain, name='adamaymain'),
    path('projects/adamaybase', views.adamayBase, name='adamaybase'),
    path('projects/addmanmonth/<int:id>', views.addManmonth, name='addmanmonth'),
    path('projects/addmanmonthid/<int:id>', views.addManmonthid, name='addmanmonthid'),
    path('projects/addispaketi/', views.addispaketi, name='addispaketi'),
    path('projects/projectsmain/projeispaketi/<int:id>', views.projeispaketi, name='projeispaketi'),
    path('projects/projectsmain/projeispaketi/update/<int:id>', views.projeispaketiupdate, name='projeispaketiupdate'),
    path('argetesvik/', views.argetesvik, name='argetesvik'),
    path('argetesvik/ekle', views.argetesvikekle, name='argetesvikekle'),
    path('argetesvik/duzenle/<int:id>', views.argetesvikduzenle, name='argetesvikduzenle'),
    path('argetesvik/sil/<int:id>', views.argetesviksil, name='argetesviksil'),
    path('fikrimulkiyet/', views.patent, name='patent'),
    path('patent/ekle', views.patentekle, name='patentekle'),
    path('patent/duzenle/<int:id>', views.patentduzenle, name='patentduzenle'),
    path('patent/sil/<int:id>', views.patentsil, name='patentsil'),
    path('bildiri/ekle', views.bildiriekle, name='bildiriekle'),
    path('bildiri/duzenle/<int:id>', views.bildiriduzenle, name='bildiriduzenle'),
    path('bildiri/sil/<int:id>', views.bildirisil, name='bildirisil'),
    path('api/data', views.apiData, name='apiData'),
    
    # path('dashboard/', views.dashboard, name='dashboard'),
    # path('login/', views.login_view, name='login'),
    # path('logout/', views.logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django_countries.fields import CountryField
from django.core.exceptions import ValidationError
from django.contrib.admin.widgets import AdminDateWidget
from django.utils import timezone
from ckeditor.fields import RichTextField
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class DepartmentList(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

    class Meta:
        db_table = "DepartmentList"
        verbose_name_plural = "Departman Listesi"

class UniversityList(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

    class Meta:
        db_table = "UniversityList"
        verbose_name_plural = "Ar-Ge Universite"

class Personel(models.Model):

    graduatedList=[
        (0, "Diğer"),
        (1, "Lise"),
        (2, "Lise (Öğrenci)"),
        (3, "Ön Lisans"),
        (4, "Ön Lisans (Öğrenci)"),
        (5, "Lisans"),
        (6, "Lisans (Öğrenci)"),
        (7, "Yüksek Lisans"),
        (8, "Yüksek Lisans (Öğrenci)"),
        (9, "Doktora"),
        (10, "Doktora (Öğrenci)")
    ]

    def validate_digit_length(self, idName):
        if not (idName.isdigit() and len(idName) == 11):
            raise ValidationError('%(idName)s en az 11 karakter olmalıdır', params={'idName': idName}, )

    name = models.CharField(max_length=30, verbose_name="Adı")
    surName = models.CharField(max_length=20, verbose_name="Soyadı")
    email = models.EmailField(max_length=50, verbose_name="Email Adresi", default="abcdefg@supsan.com")
    gender = models.IntegerField(choices=((1,"Erkek"),(2,"Kadın")),default=1, verbose_name="Cinsiyet")
    birthDay=models.DateField(("Doğum Tarihi"), auto_now=False, auto_now_add=False)
    idName = models.CharField(max_length=11, verbose_name="T.C. Kimlik No", default='12345678911')
    country = CountryField(verbose_name="Uyruk", default='TR')
    sgNumber = models.IntegerField(null=True, blank=True, verbose_name="Sosyal Güvenlik Numarası")
    sNumber = models.IntegerField(null=True, blank=True, verbose_name="Sicil No")
    department = models.ForeignKey(DepartmentList, on_delete=models.SET_DEFAULT, verbose_name="Çalıştığı Departman", default=0, related_name="PersonelDepartman")
    respons = models.IntegerField(choices=((1,"Araştırmacı"),(2,"Teknisyen"),(3, "Destek Personeli")),default=1, verbose_name="Ar-Ge Görevi")
    startDate = models.DateField(null=True, blank=True, verbose_name="İşe Başlangıç Tarihi")
    finisDate = models.DateField(null=True, blank=True, verbose_name="İşten Ayrılış Tarihi")
    rdfinisDate = models.DateField(null=True, blank=True, verbose_name="Ar-Ge Ayrılış Tarihi")
    rdStartDate= models.DateField(null=True, blank=True, verbose_name="Ar-Ge Merkezi İşe Başlama Tarihi")
    graduated = models.IntegerField(choices=graduatedList, default=0, verbose_name="Tahsil Durumu")
    hschool = models.CharField(null=True, blank=True, max_length=50, verbose_name="Lise Adı",)
    hschooldist = models.CharField(null=True, blank=True, max_length=50, verbose_name="Lise Bölümü",)
    huschool = models.ForeignKey(UniversityList,on_delete=models.SET_DEFAULT, verbose_name="Universite (Ön Lisans)", default=1, related_name='onlisans')
    huschooldist = models.CharField(null=True, blank=True, max_length=50, verbose_name="Bölümü (Ön Lisans)",)
    university = models.ForeignKey(UniversityList,on_delete=models.SET_DEFAULT, verbose_name="Universite (Lisans)", default=1, related_name='lisans')
    universitydist = models.CharField(null=True, blank=True, max_length=50, verbose_name="Bölümü (Lisans)",)
    masteruniversity = models.ForeignKey(UniversityList,on_delete=models.SET_DEFAULT, verbose_name="Universite (Yüksek Lisans)", default=1,related_name='master')
    masteruniversitydist = models.CharField(null=True, blank=True, max_length=50, verbose_name="Bölümü (Yüksek Lisans")
    druniversity = models.ForeignKey(UniversityList,on_delete=models.SET_DEFAULT, verbose_name="Universite (Doktora)", default=1,related_name='doktora')
    druniversitydist = models.CharField(null=True, blank=True, max_length=50, verbose_name="Bölümü (Doktora")
    userImg = models.ImageField(upload_to='personels/img/', blank = True, null = True, verbose_name="Kullanıcı Profil Resmi")
    expensecenter = models.IntegerField(("Masraf Yeri"), choices=((4001,"4001"),(4002,"4002")), blank=True, null=True, default=4001)

    def __str__(self):
        return f"{self.name},{self.surName}"

    class Meta:
        db_table = "personel"
        verbose_name_plural = "Ar-Ge Personeller"

class News(models.Model):
    title = models.CharField(("Başlık"), max_length=100)
    body = models.TextField(("Gövde"), max_length=500)
    content = RichTextField()
    addedDate = models.DateField(("Haber Eklme Tarihi"),null = True, blank=True, default=timezone.now)
    updateDate = models.DateField(("Haber Güncelleme Tarihi"),null = True, blank=True, default=timezone.now)
    newsImg = models.ImageField(upload_to='news/img/', blank=True, null=True, verbose_name="Haber Görseli")

    def __str__(self):
        return f"{self.title}"

    class Meta:
        db_table = "Haberler"
        verbose_name_plural = "Ar-Ge Haberler"
        ordering=['-updateDate']

class Projects(models.Model):
    ProjeDurumu = models.IntegerField(("Proje Durumu:"), choices=((0,"Seçiniz"),(1,"Tamamlandı"),(2,"Devam Ediyor"),(3,"İptal")), default=0)
    ProjeKodu = models.CharField(("Proje Kodu:"), max_length=50)
    ProjeAdi= models.CharField(("Proje Adı:"), max_length=120)
    ProjeYurutucusu= models.ForeignKey(Personel, verbose_name=("Proje Yürütücüsü"), on_delete=models.CASCADE,blank=True,null=True, related_name="Proje_Y")
    ProjeBaslamaTarihi = models.DateField(("Proje Başlama Tarihi:"), null=True, blank=True)
    ProjeBitisTarihi= models.DateField(("Proje Bitiş Tarihi:"), null=True, blank=True)
    TamamlanmaYuzdesi = models.FloatField(("Projenin Tamamlanma Yüzdesi"),max_length=2,default=0, validators = [MinValueValidator(0), MaxValueValidator(100)])
    ProjeSuresiAdamAy=models.IntegerField(("Proje Adam Ay Süresi:"), null=True, blank=True)
    ProjeKonusu= models.TextField(("Proje Konusu:"), max_length=1000)
    ProjeOzeti= models.TextField(("Proje Özeti:"), max_length=1000)
    UlusalDestek= models.BooleanField(("Ulusal Destek Prgramı Var Mı?"), default=False)
    UlusalDestekTanim= models.CharField(("Ulusal Destek Adı:"), max_length=50, null=True, blank=True)
    OzKaynakTutar= models.DecimalField(("Öz Kaynaklarca Karşılanan tutar (TL):"), max_digits=10, decimal_places=2,null=True, blank=True)
    DestekTutari=models.DecimalField(("Destek Tutarı (TL):"), max_digits=10, decimal_places=2,null=True, blank=True)
    ToplamProjeButcesi= models.DecimalField(("Toplam Proje Bütçesi"), max_digits=10, decimal_places=2,null=True, blank=True)
    HizmetAlimiKonusu= models.CharField(("Hizmet Alımı Konusu:"), max_length=50, null=True, blank=True)
    HizmetAlimi=models.IntegerField(("Hizmet Alımı Yapılan Yer"),choices=((0,"Hizmet Alımı Yapılmadı"),(1,"Yurt İçi"),(2,"Yurt Dışı"),(3,"Her İkisi")), default=0)
    YurtIciHizmetAlimiTutari=models.IntegerField(("Yurt İçi Hizmet Alımı Tutarı (TL):"), default=0, null=True, blank=True)
    YurtDisiHizmetAlimiTutari=models.IntegerField(("Yurt Dışı Hizmet Alımı Tutarı (TL):"), default=0, null=True, blank=True)
    ProjeKonusunuBelirleyenIhtiyaclar=models.TextField(("Projenin Konusunu Belirleyen İhtiyaçlar:"),null=True, blank=True, max_length=5000)
    ProjeKapsamindaYapilacakFaaliyetler= models.TextField(("Proje Kapsamında Yapılacak Faaliyetler:"),null=True, blank=True, max_length=5000)
    ProjeninYenilikciYonuArgeNiteligi=models.TextField(("Projenin Yenilikçi Yönü ve AR-GE Niteliği:"),null=True, blank=True, max_length=5000)
    ProjeninBeklenenCiktilariFaydalari=models.TextField(("Projenin Beklenen Çıktıları:"),null=True, blank=True, max_length=5000)
    ProjePersonel= models.IntegerField(("Projedeki Personel Sayısı:"),null=True, blank=True)
    UniversiteSanayiIsbirligiProjesi=models.IntegerField(("Üniversite-Sanayi İşbirliği Mi?"), choices=((0,"Seçiniz"),(1,"Evet"),(2,"Hayır")),default=0)
    FirmalarArasiArgeIsbirligi=models.IntegerField(("Firmalar Arası Ar-Ge İşbirliği Mi?"), choices=((0,"Seçiniz"),(1,"Evet"),(2,"Hayır")),default=0)
    SipariseDayaliArgeProjesi=models.IntegerField(("Siparişe Dayalı Ar-Ge Projesi Mi?"), choices=((0,"Seçiniz"),(1,"Evet"),(2,"Hayır")),default=0)
    ProjeGuncellemeTarihi=models.DateField(("Projenin Güncelleme Tarihi:"),null=True, blank=True)
    PRojeCiktisi= models.IntegerField(("Projenin Çıktısı"),choices=((0,"Seçiniz"),(1,"Ticari Ürün"),(2,"Proses Geliştirme"),(3,"Bilgi Birikimi ve Yetkinlik Kazanımı")),default=0)
    projecalis = models.ManyToManyField(Personel, verbose_name=("Projede Çalışan Personeller:"),related_name="Proje_adam_ay", through="AdamAy")

    def __str__(self):
        return f"{self.ProjeKodu}"
    
    class Meta:
        db_table = "Projeler"
        verbose_name_plural = "Ar-Ge Projeler"

class IsPaketiekle(models.Model):
    projeKodu = models.ForeignKey(Projects, verbose_name=("Proje Kodu"), on_delete=models.CASCADE, null=True)
    isPaketino = models.IntegerField(("İş Paketi No:"), choices=((1,"IP.1"), (2,"IP.2"), (3,"IP.3"), (4,"IP.4"), (5,"IP.5"), (6,"IP.6")), default=1)
    isPaketiadi = models.CharField(("İş Paketi Başlığı"), max_length=100, default="İş Paketi Başlığı") 
    sorumlu = models.ForeignKey(Personel, verbose_name=("İş Paketi Sorumlusu"), on_delete=models.CASCADE, null=True)
    baslangicTarihi = models.DateField(("İş Paketi Başlangıcı"), null=True, blank=True)
    bitisTarihi = models.DateField(("İş Paketi Bitişi"), null=True, blank=True)
    tamamlanmaOranı = models.FloatField(("Projenin Tamamlanma Yüzdesi"),max_length=2,default=0, validators = [MinValueValidator(0), MaxValueValidator(100)])

templates/core/adamaymain.html
{% extends 'core/base.html' %}
{% load static %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Ana Sayfa</a></li>
    <li class="breadcrumb-item"><a href="{% url 'core:projectsmain' %}"> Projeler</a></li>
    <li class="breadcrumb-item passive">Projeler Adam-Ay</li>
{% endblock breadcrumb %}
{% block breadcrumb_menu %}
   <form>
        {% csrf_token %}
        <input type="text", name="keyword", class="input-group-sm", maxlength="64", placeholder="Ara">
        <button type="submit", class="btn btn-gray-100 btn-outline-blue"><i class="fa fa-search"></i></button>
    </form>
    {% if user.is_authenticated  %}
    <a class="btn btn-gray-100 btn-outline-blue", href="{% url 'core:adamaybase' %}"><i class="fa fa-diagnoses"></i> Dönemsel Adam/Ay Oranları</a>
    {% endif %}
{% endblock breadcrumb_menu %}
{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <strong> {{projects.count}} Devam Eden Proje</strong>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12">
                    <table class="table table-responsive-sm table-hover table-outline mb-5 ">
                        <thead class="thead-light">
                            <tr>
                                <th><i class="fa fa-gavel"></i></th>
                                <th>Proje Kodu</th>
                                <th>Proje Adı</th>
                                <th>Adam/Ay Ekle</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for project in projects %}
                            <tr>
                                <td>
                                    <div><span class="badge badge-pill badge-gray-200"># {{forloop.counter}}</span></div>
                                </td>
                                <td>
                                    <div><a href="{% url 'core:projectdetail' project.id %}">{{ project.ProjeKodu }} </a></div>
                                </td>
                                <td>
                                    <div><a href="{% url 'core:projectdetail' project.id %}">{{ project.ProjeAdi }} </a></div>
                                </td>
                                <td>
                                    <div><a href="{% url 'core:addmanmonth' project.id %}"> <span class="badge badge-pill badge-cyan" style="width: 100px; height: 20px;">Adam/Ay Ekle</span></a></div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/core/detailperson.html
{% extends 'core/base.html' %}
{% load static %}

{% block breadcrumb %}
        <li class="breadcrumb-item"><a  href="{% url 'core:index' %}" >Ana Sayfa</a></li>
        <li class="breadcrumb-item"><a  href="{% url 'core:personelmain' %}" >Personeller</a></li>
        <li class="breadcrumb-item">Personel Detayı</li>
{% endblock breadcrumb%}
 
{% block breadcrumb_menu %}
    {% if user.is_authenticated  %}
    <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
        <div class="btn-group" role="group">
            <button id="btnGroupDrop1" type="button" class="btn btn-transparent" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bars"></i>
            Personel Güncellemeleri
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item", href="{% url 'core:personelupdate' person.id %}"><i class="fa fa-retweet"></i> Personel Güncelle </a>
                <a class="dropdown-item", href="{% url 'core:addmanmonthid' person.id %}"><i class="fa fa-diagnoses"></i> Adam/Ay Güncelle </a>
                <a class="dropdown-item", href="#"><i class="fa fa-clipboard-list"></i> Blasasda </a>
            </div>
        </div>
        <a class="btn btn-gray-100 btn-outline-blue", href="{% url 'core:addpersonel' %}"><i class="fa fa-user-plus"></i> Personel Ekle </a>
        <a class="btn" href="{% url 'core:exportPerson' person.id %}"><i class="fa fa-download"></i> Personel Export </a>
    </div>
    
    
    
    {% endif %}
{% endblock breadcrumb_menu %}

{% block content %}

<div class="container-fluid">
    <div id="ui-view" style="opacity: 1;">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-12 mb-3">
                    <div class="social-box" style="height:110%">
                        {% if person.userImg %}
                        <img src="{{ person.userImg.url }}" class="img-avatar m-4" alt="{{ user_view }}" width="20%">
                        {% else %}
                        <img src="{% static 'core/avatar/blank_profile.png' %}" class="img-avatar m-4" width="20%">
                        {% endif %}
                        <ul>
                        <li>
                            <strong> {{manmonthsum.adamAylar__sum|floatformat:2}} </strong>
                            <span>TOPLAM ADAM/AY</span>
                        </li>
                        <li>
                            <strong>{% for count in manmonth %} {{count.total}} {% endfor %}</strong>
                            <span>PROJE</span>
                        </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card mt-5">
                        <div class="simple-box">
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <ul class="mt-4 mx-5">
                                        <h5>Kişisel Bilgiler</h5>
                                        <li><span>İsim:</span> {{ person.name }} {{ person.surName }}</li>
                                        <li><span>Doğum Tarihi:</span> {{ person.birthDay }}</li>
                                        <li><span>E-mail:</span> {{ person.email}}</li>
                                        <li><span>Uyruk:</span> {{ person.get_country_display }}</li>
                                        <li><span>T.C. No:</span> {{ person.idName }}</li>
                                    </ul>
                                </div>
                                <div class="col-12 col-md-6 text-left">
                                    <ul class="mt-4 mx-5">
                                        <h5>Çalışan Bilgileri</h5>
                                        <li><span>Departman:</span> {{person.department}}</li>
                                        <li><span>Görevi:</span> {{ person.get_respons_display }}</li>
                                        <li><span>Sicil No:</span> {{ person.sNumber }}</li>
                                        <li><span>İşe Başlangıç Tarihi:</span> {{ person.startDate}}</li>
                                        <li><span>Ar-Ge Başlangıç Tarihi:</span> {{ person.rdStartDate }}</li>
                                        <li><span>İşten Ayrılış Tarihi:</span> {{ person.finisDate|default_if_none:"-" }}</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card mt-5">
                        <div class="simple-box">
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <ul class="mt-4 mx-5">
                                    <h5>Eğitim Bilgileri</h5>
                                    <li><span>Mezuniyet Derecesi:</span> {{ person.get_graduated_display }}</li>
                                    <li><span>Lise Adı:</span> {{ person.hschool|default_if_none:"-" }}</li>
                                    <li><span>Bölüm (lise):</span> {{ person.hschooldist|default_if_none:"-"}}</li>
                                    <li><span>Ön Lisans Üniversite Adı:</span> {{ person.huschool|default_if_none:"-" }}</li>
                                    <li><span>Bölüm (Ön Lisans):</span> {{ person.huschooldist|default_if_none:"-"}}</li>
                                    <li><span>Lisans Üniversite Adı:</span> {{ person.university|default_if_none:"-" }}</li>
                                    <li><span>Bölüm (Lisans):</span> {{ person.universitydist|default_if_none:"-"}}</li>
                                    <li><span>Yüksek Lisans Üniversite Adı:</span> {{ person.masteruniversity|default_if_none:"-" }}</li>
                                    <li><span>Bölüm (Yüksek Lisans):</span> {{ person.masteruniversitydist|default_if_none:"-"}}</li>
                                    <li><span>Doktora Üniversite Adı:</span> {{ person.druniversity|default_if_none:"-" }}</li>
                                    <li><span>Bölüm (Doktara):</span> {{ person.druniversitydist|default_if_none:"-"}}</li>
                                    </ul>
                                </div>
                                <div class="col-12 col-md-6">
                                    <ul class="mt-4 mx-5">
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

templates/core/projeispaketi.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block breadcrumb %}
        <li class="breadcrumb-item"><a  href="{% url 'core:index' %}" >Ana Sayfa</a></li>
        <li class="breadcrumb-item"><a  href="{% url 'core:projectsmain' %}" >Projeler</a></li>
        <li class="breadcrumb-item"><a href="{% url 'core:projectdetail' project.id %}">Proje Detayı</a></li>
        <li class="breadcrumb-item passive">İş Paketleri</li>
{% endblock breadcrumb %}


{% block breadcrumb_menu %}
    {% if user.is_authenticated  %}
    <a class="btn btn-gray-100 btn-outline-blue", href="{% url 'core:addispaketi' %}"><i class="fa fa-plus-circle"></i>  İş Paketi Ekle</a>
    <a class="btn btn-gray-100 btn-outline-blue", href="{% url 'core:exportprojects' %}"><i class="fa fa-download"></i>  Export</a>
    {% endif %}
{% endblock breadcrumb_menu %}

{% block content %}

<div class="col-sm-12">
    <div class="card">
        <div class="card-header">
            <strong> {{project.ProjeKodu}} İş Paketi Listesi</strong>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-12">
                    <p class="font-weight-normal">* İş Paketini Güncellemek İçin Tıklayınız...</p>
                    <div class="col-sm-12">
                    <table class="table table-responsive-sm table-hover table-outline mb-5">
                        <thead class="thead-light">
                            <tr>
                                <th>Paket No</th>
                                <th>İş Paketi Adı*</th>
                                <th>Başlangıç Tarihi</th>
                                <th>Bitiş Tarihi</th>
                                <th>İş Paketi Sorumlusu</th>
                                <th>Tamamlanma Oranı</th>
                                <th>Yapılacak Faaliyet</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for query in querylist %}
                            <tr>
                                <td class="text-center font-weight-bold">{{query.isPaketino}}</td>
                                <td><a href="{% url 'core:projeispaketiupdate' query.id %}">{{query.isPaketiadi}}</a></td>
                                <td>{{query.baslangicTarihi}}</td>
                                <td>{{query.bitisTarihi}}</td>
                                <td>{{query.sorumlu}}</td>
                                <td>{{query.tamamlanmaOranı}}</td>
                                <td>{{query.faaliyet}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    
                    
                    
</div>
</div>
</div>
</div>
</div>
</div>
{% endblock content %}